version: '3'
services:
  imobsite:
    build: .
    container_name: imobsite-crm
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_FIREBASE_API_KEY=AIzaSyBIe3S6v12OABxSC7fJCgbONhusqEKYdB4
      - VITE_FIREBASE_PROJECT_ID=projetoimobsite
      - VITE_FIREBASE_APP_ID=1:659864253826:web:be28e2b76da214a9d28b9b
      - PORT=3000
      - SESSION_SECRET=imobsite-secret-key
      - NODE_ENV=production